# ==== DataSource (PROD) ====
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari (PROD)
spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX:15}
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN:3}
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.idle-timeout=600000

# JPA (PROD)
spring.jpa.show-sql=false

# JWT Config (Se inyecta estrictamente por variable de entorno)
mi-tienda.jwt.secret=${JWT_SECRET}
JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS:86400000}
JWT_ISSUER=${JWT_ISSUER:mi-tienda}
JWT_AUDIENCE=${JWT_AUDIENCE:mi-tienda-web}

# Mailjet (PROD - Se inyecta estrictamente por variable de entorno)
mailjet.apikey.public=${MAILJET_PUBLIC}
mailjet.apikey.private=${MAILJET_PRIVATE}

# Exponer solo lo necesario
management.endpoint.health.show-details=never
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# Token para /actuator/** (excepto health)
health.api.token=${HEALTHCHECK_TOKEN}

# Frontend Producción
url.login=https://minventario.net